db = db.getSiblingDB(process.env.MONGO_INITDB_DATABASE); // udma
db.createUser({
    user: process.env.MONGO_INITDB_ROOT_USERNAME,
    pwd: process.env.MONGO_INITDB_ROOT_PASSWORD,
    roles: [{
        role: "readWrite",
        db: process.env.MONGO_INITDB_DATABASE,
    }]
});
db.createCollection(process.env.MAIN_DB_COLLECTION); // medical_records
db[process.env.MAIN_DB_COLLECTION].insertMany([
    {
        "URI": "medical_record_1.pdf",
        "UDA": "12345",
        "Anno Ricovero": "2023",
        "Numero Ricovero": "56789",
        "Regime": "Ordinario.",
        "Data Ricovero": "15/06/2023",
        "Reparto Accettazione": "Medicina Generale",
        "Tipo Ricovero": "Urgenza",
        "Reparto Dimissione": "Medicina Generale",
        "Data Dimissione": "20/06/2023",
        "Anamnesi": "Paziente con storia di ipertensione arteriosa, obesità moderata e fumo di sigaretta da 15 anni.",
        "Diagnosi": "Insufficienza cardiaca congestizia con edema polmonare.",
        "Terapia": "Terapia diuretica, ACE inibitori, beta-bloccanti.",
        "Keywords": "Scompenso, Insufficienza cardiaca, Edema polmonare.",
        "Nome": "Luca",
        "Cognome": "Neri",
        "Sesso": "M",
        "Data di nascita": "03/06/1990",
        "Codice Fiscale": "NRILCU90H03H501V",
        "_id": "NRILCU90H03H501V_12345"
    },
    {
        "URI": "medical_record_2.pdf",
        "UDA": "67890",
        "Anno Ricovero": "2022",
        "Numero Ricovero": "45678",
        "Regime": "Day Hospital",
        "Data Ricovero": "10/11/2022",
        "Reparto Accettazione": "Endocrinologia",
        "Tipo Ricovero": "Ordinario",
        "Reparto Dimissione": "Endocrinologia",
        "Data Dimissione": "12/11/2022",
        "Anamnesi": "Paziente con anamnesi di diabete mellito di tipo 2, neuropatia diabetica e ipertensione arteriosa.",
        "Diagnosi": "Ulcera diabetica al piede destro con infezione locale.",
        "Terapia": "Terapia antibiotica, medicazioni avanzate, consulenza podologica.",
        "Keywords": "Diabete, Ulcera, Infezione",
        "Nome": "Marco",
        "Cognome": "Rossi",
        "Sesso": "M",
        "Data di nascita": "15/03/1970",
        "Codice Fiscale": "RSSMRC70C15H501U",
        "_id": "RSSMRC70C15H501U_67890"
    },
    {
        "URI": "medical_record_3.pdf",
        "UDA": "34567",
        "Anno Ricovero": "2021",
        "Numero Ricovero": "98765",
        "Regime": "Ordinario",
        "Data Ricovero": "05/07/2021",
        "Reparto Accettazione": "Ortopedia",
        "Tipo Ricovero": "Programmatico",
        "Reparto Dimissione": "Ortopedia.",
        "Data Dimissione": "10/07/2021",
        "Anamnesi": "Pregresso trauma sportivo con lesione meniscale, dolore articolare ricorrente.",
        "Diagnosi": "Rottura menisco mediale ginocchio destro con versamento articolare.",
        "Terapia": "Fisioterapia post-operatoria.",
        "Keywords": "Rottura menisco mediale ginocchio destro con versamento articolare:\n\n- Frattura\n- Emorragia\n- Versamento articolare",
        "Nome": "Luca",
        "Cognome": "Neri",
        "Sesso": "M",
        "Data di nascita": "03/06/1990",
        "Codice Fiscale": "NRILCU90H03H501V",
        "_id": "NRILCU90H03H501V_34567"
    },
    {
        "URI": "medical_record_4.pdf",
        "UDA": "45678",
        "Anno Ricovero": "2023",
        "Numero Ricovero": "11223",
        "Regime": "Urgenza",
        "Data Ricovero": "30/08/2023",
        "Reparto Accettazione": "Ginecologia",
        "Tipo Ricovero": "Urgenza",
        "Reparto Dimissione": "Ginecologia",
        "Data Dimissione": "03/09/2023",
        "Anamnesi": "Storia di endometriosi, dolori pelvici ricorrenti, amenorrea secondaria.",
        "Diagnosi": "Gravidanza ectopica con emorragia intra-addominale.",
        "Terapia": "Intervento chirurgico laparoscopico.",
        "Keywords": "Emorragia",
        "Nome": "Laura",
        "Cognome": "Bianchi",
        "Sesso": "F",
        "Data di nascita": "22/08/1982",
        "Codice Fiscale": "BNCLRA82M62H501X",
        "_id": "BNCLRA82M62H501X_45678"
    },
    {
        "URI": "medical_record_5.pdf",
        "UDA": "78901",
        "Anno Ricovero": "2020",
        "Numero Ricovero": "33456",
        "Regime": "Day Hospital",
        "Data Ricovero": "18/04/2020",
        "Reparto Accettazione": "Dermatologia",
        "Tipo Ricovero": "Ordinario",
        "Reparto Dimissione": "Dermatologia.",
        "Data Dimissione": "20/04/2020",
        "Anamnesi": "Pregressa dermatite atopica, familiarità per psoriasi, stress cronico.",
        "Diagnosi": "Psoriasi a placche estesa su arti e tronco.",
        "Terapia": "Terapia topica con corticosteroidi, fototerapia UVB, supporto psicologico.",
        "Keywords": "Psoriasi",
        "Nome": "Marco",
        "Cognome": "Rossi",
        "Sesso": "M",
        "Data di nascita": "15/03/1970",
        "Codice Fiscale": "RSSMRC70C15H501U",
        "_id": "RSSMRC70C15H501U_78901"
    },
    {
        "URI": "medical_record_6.pdf",
        "UDA": "11223",
        "Anno Ricovero": "2023",
        "Numero Ricovero": "33445",
        "Regime": "Ordinario",
        "Data Ricovero": "02/05/2023",
        "Reparto Accettazione": "Neurologia",
        "Tipo Ricovero": "Urgenza",
        "Reparto Dimissione": "Neurologia",
        "Data Dimissione": "08/05/2023",
        "Anamnesi": "Episodi di emicrania con aura, ipotensione ortostatica.",
        "Diagnosi": "Crisi epilettica focale.",
        "Terapia": "Antiepilettici",
        "Keywords": "Non associate.",
        "Nome": "Laura",
        "Cognome": "Bianchi",
        "Sesso": "F",
        "Data di nascita": "22/08/1982",
        "Codice Fiscale": "BNCLRA82M62H501X",
        "_id": "BNCLRA82M62H501X_11223"
    },
    {
        "URI": "medical_record_7.pdf",
        "UDA": "99887",
        "Anno Ricovero": "2022",
        "Numero Ricovero": "55678",
        "Regime": "Day Hospital",
        "Data Ricovero": "10/09/2022",
        "Reparto Accettazione": "Cardiologia",
        "Tipo Ricovero": "Ordinario",
        "Reparto Dimissione": "Cardiologia",
        "Data Dimissione": "12/09/2022",
        "Anamnesi": "Ipertensione arteriosa, obesità moderata, fumo.",
        "Diagnosi": "Angina instabile.",
        "Terapia": "Antiaggreganti, beta-bloccanti, nitrati.",
        "Keywords": "Infarto",
        "Nome": "Laura",
        "Cognome": "Bianchi",
        "Sesso": "F",
        "Data di nascita": "22/08/1982",
        "Codice Fiscale": "BNCLRA82M62H501X",
        "_id": "BNCLRA82M62H501X_99887"
    },
    {
        "URI": "medical_record_8.pdf",
        "UDA": "33456",
        "Anno Ricovero": "2021",
        "Numero Ricovero": "77889",
        "Regime": "Ordinario",
        "Data Ricovero": "15/06/2021",
        "Reparto Accettazione": "Endocrinologia",
        "Tipo Ricovero": "Programmatico",
        "Reparto Dimissione": "Endocrinologia",
        "Data Dimissione": "17/06/2021",
        "Anamnesi": "Diabete tipo 2, neuropatia diabetica.",
        "Diagnosi": "Complicanza metabolica con chetoacidosi lieve.",
        "Terapia": "Insulinoterapia.",
        "Keywords": "Diabete",
        "Nome": "Marco",
        "Cognome": "Rossi",
        "Sesso": "M",
        "Data di nascita": "15/03/1970",
        "Codice Fiscale": "RSSMRC70C15H501U",
        "_id": "RSSMRC70C15H501U_33456"
    },
    {
        "URI": "medical_record_9.pdf",
        "UDA": "22567",
        "Anno Ricovero": "2023",
        "Numero Ricovero": "99234",
        "Regime": "Urgenza.",
        "Data Ricovero": "14/10/2023",
        "Reparto Accettazione": "Chirurgia Generale.",
        "Tipo Ricovero": "Urgenza",
        "Reparto Dimissione": "Chirurgia Generale",
        "Data Dimissione": "20/10/2023",
        "Anamnesi": "Dolore addominale acuto, febbre.",
        "Diagnosi": "Appendicite acuta perforata.",
        "Terapia": "Appendicectomia laparoscopica, terapia antibiotica.",
        "Keywords": "Infezione, Emorragia, Perforata",
        "Nome": "Laura",
        "Cognome": "Bianchi",
        "Sesso": "F",
        "Data di nascita": "22/08/1982",
        "Codice Fiscale": "BNCLRA82M62H501X",
        "_id": "BNCLRA82M62H501X_22567"
    },
    {
        "URI": "medical_record_10.pdf",
        "UDA": "56987",
        "Anno Ricovero": "2022",
        "Numero Ricovero": "12569",
        "Regime": "Ordinario",
        "Data Ricovero": "07/07/2022",
        "Reparto Accettazione": "Dermatologia",
        "Tipo Ricovero": "Programmatico",
        "Reparto Dimissione": "Dermatologia",
        "Data Dimissione": "09/07/2022",
        "Anamnesi": "Dermatite atopica cronica, stress.",
        "Diagnosi": "Peggioramento psoriasi a placche.",
        "Terapia": "Fototerapia UVB e farmaci biologici.",
        "Keywords": "Psoriasi",
        "Nome": "Marco",
        "Cognome": "Rossi",
        "Sesso": "M",
        "Data di nascita": "15/03/1970",
        "Codice Fiscale": "RSSMRC70C15H501U",
        "_id": "RSSMRC70C15H501U_56987"
    },
    {
        "URI": "medical_record_11.pdf",
        "UDA": "77889",
        "Anno Ricovero": "2023",
        "Numero Ricovero": "44556",
        "Regime": "Ordinario",
        "Data Ricovero": "12/09/2023",
        "Reparto Accettazione": "Pneumologia",
        "Tipo Ricovero": "Urgenza",
        "Reparto Dimissione": "Pneumologia",
        "Data Dimissione": "18/09/2023",
        "Anamnesi": "Asma bronchiale cronica, allergie respiratorie.",
        "Diagnosi": "Polmonite interstiziale.",
        "Terapia": "Antibiotici, cortisonici, ossigenoterapia.",
        "Keywords": "Polmonite interstiziale è associata alle seguenti parole chiave: ['Polmonite'].",
        "Nome": "Luca",
        "Cognome": "Neri",
        "Sesso": "M",
        "Data di nascita": "03/06/1990",
        "Codice Fiscale": "NRILCU90H03H501V",
        "_id": "NRILCU90H03H501V_77889"
    },
    {
        "URI": "medical_record_12.pdf",
        "UDA": "88990",
        "Anno Ricovero": "2022",
        "Numero Ricovero": "55667",
        "Regime": "Day Hospital",
        "Data Ricovero": "22/11/2022",
        "Reparto Accettazione": "Reparto Accettazione: Reumatologia",
        "Tipo Ricovero": "Ordinario",
        "Reparto Dimissione": "Reumatologia.",
        "Data Dimissione": "24/11/2022",
        "Anamnesi": "Artrite reumatoide diagnosticata da 5 anni, rigidità articolare mattutina.",
        "Diagnosi": "Riacutizzazione artrite reumatoide.",
        "Terapia": "Immunosoppressori, corticosteroidi, fisioterapia.",
        "Keywords": "Artrite reumatoide.",
        "Nome": "Marco",
        "Cognome": "Rossi",
        "Sesso": "M",
        "Data di nascita": "15/03/1970",
        "Codice Fiscale": "RSSMRC70C15H501U",
        "_id": "RSSMRC70C15H501U_88990"
    },
    {
        "URI": "medical_record_13.pdf",
        "UDA": "99001",
        "Anno Ricovero": "2023",
        "Numero Ricovero": "66778",
        "Regime": "Ordinario",
        "Data Ricovero": "05/05/2023",
        "Reparto Accettazione": "Gastroenterologia.",
        "Tipo Ricovero": "Urgenza",
        "Reparto Dimissione": "Gastroenterologia",
        "Data Dimissione": "10/05/2023",
        "Anamnesi": "Pregresse ulcere gastriche, dolore epigastrico acuto.",
        "Diagnosi": "Ulcera peptica perforata.",
        "Terapia": "Terapia antibiotica, IPP, intervento chirurgico.",
        "Keywords": "Ulcera peptica perforata",
        "Nome": "Marco",
        "Cognome": "Rossi",
        "Sesso": "M",
        "Data di nascita": "15/03/1970",
        "Codice Fiscale": "RSSMRC70C15H501U",
        "_id": "RSSMRC70C15H501U_99001"
    },
    {
        "URI": "medical_record_14.pdf",
        "UDA": "11234",
        "Anno Ricovero": "2021",
        "Numero Ricovero": "77890",
        "Regime": "Urgenza",
        "Data Ricovero": "10/07/2021",
        "Reparto Accettazione": "Ostetricia",
        "Tipo Ricovero": "Urgenza",
        "Reparto Dimissione": "Ostetricia",
        "Data Dimissione": "15/07/2021",
        "Anamnesi": "Gravidanza a termine, ipertensione gestazionale.",
        "Diagnosi": "Preeclampsia con segni di sofferenza fetale.",
        "Terapia": "Taglio cesareo d'urgenza.",
        "Keywords": "Preeclampsia con segni di sofferenza fetale. Sofferenza fetale, Preeclampsia.",
        "Nome": "Laura",
        "Cognome": "Bianchi",
        "Sesso": "F",
        "Data di nascita": "22/08/1982",
        "Codice Fiscale": "BNCLRA82M62H501X",
        "_id": "BNCLRA82M62H501X_11234"
    },
    {
        "URI": "medical_record_15.pdf",
        "UDA": "22345",
        "Anno Ricovero": "2020",
        "Numero Ricovero": "88901",
        "Regime": "Day Hospital.",
        "Data Ricovero": "12/03/2020",
        "Reparto Accettazione": "Oculistica",
        "Tipo Ricovero": "Ordinario",
        "Reparto Dimissione": "Oculistica.",
        "Data Dimissione": "13/03/2020",
        "Anamnesi": "Miopia elevata, episodi di distacco vitreale.",
        "Diagnosi": "Distacco di retina parziale.",
        "Terapia": "Laserterapia retinica.",
        "Keywords": "**Distacco di retina parziale è associato a \"Emorragia\" e \"Lesione\".**",
        "Nome": "Marco",
        "Cognome": "Rossi",
        "Sesso": "M",
        "Data di nascita": "15/03/1970",
        "Codice Fiscale": "RSSMRC70C15H501U",
        "_id": "RSSMRC70C15H501U_22345"
    },
    {
        "URI": "medical_record_16.pdf",
        "UDA": "99123",
        "Anno Ricovero": "2023",
        "Numero Ricovero": "67890",
        "Regime": "Ordinario",
        "Data Ricovero": "15/09/2023",
        "Reparto Accettazione": "Gastroenterologia",
        "Tipo Ricovero": "Urgenza",
        "Reparto Dimissione": "Gastroenterologia",
        "Data Dimissione": "22/09/2023",
        "Anamnesi": "Pregresse ulcere gastriche, dolore epigastrico acuto.",
        "Diagnosi": "Ulcera peptica perforata.",
        "Terapia": "Terapia antibiotica e IPP.",
        "Keywords": "Ulcera peptica perforata è associato alle seguenti parole chiave:\n\n- Emorragia\n- Infezione\n- Lesione\n- Infiammazione\n- Ulcera",
        "Nome": "Luca",
        "Cognome": "Neri",
        "Sesso": "M",
        "Data di nascita": "03/06/1990",
        "Codice Fiscale": "NRILCU90H03H501V",
        "_id": "NRILCU90H03H501V_99123"
    },
    {
        "URI": "medical_record_17.pdf",
        "UDA": "99234",
        "Anno Ricovero": "2022",
        "Numero Ricovero": "11234",
        "Regime": "Day Hospital",
        "Data Ricovero": "20/05/2022",
        "Reparto Accettazione": "Endocrinologia",
        "Tipo Ricovero": "Ordinario",
        "Reparto Dimissione": "Endocrinologia.",
        "Data Dimissione": "22/05/2022",
        "Anamnesi": "Diabete tipo 2, neuropatia diabetica.",
        "Diagnosi": "Chetoacidosi diabetica lieve.",
        "Terapia": "Insulinoterapia, idratazione.",
        "Keywords": "Diabete, Glicemia",
        "Nome": "Marco",
        "Cognome": "Rossi",
        "Sesso": "M",
        "Data di nascita": "15/03/1970",
        "Codice Fiscale": "RSSMRC70C15H501U",
        "_id": "RSSMRC70C15H501U_99234"
    },
    {
        "URI": "medical_record_18.pdf",
        "UDA": "99345",
        "Anno Ricovero": "2021",
        "Numero Ricovero": "22345",
        "Regime": "Ordinario",
        "Data Ricovero": "10/11/2021",
        "Reparto Accettazione": "Neurologia",
        "Tipo Ricovero": "Programmatico.",
        "Reparto Dimissione": "Neurologia.",
        "Data Dimissione": "15/11/2021",
        "Anamnesi": "Pregresse crisi epilettiche focali.",
        "Diagnosi": "Monitoraggio per epilessia.",
        "Terapia": "Aggiustamento terapia antiepilettica.",
        "Keywords": "Non ci sono parole chiave associate al testo \"Monitoraggio per epilessia\".",
        "Nome": "Laura",
        "Cognome": "Bianchi",
        "Sesso": "F",
        "Data di nascita": "22/08/1982",
        "Codice Fiscale": "BNCLRA82M62H501X",
        "_id": "BNCLRA82M62H501X_99345"
    },
    {
        "URI": "medical_record_19.pdf",
        "UDA": "99456",
        "Anno Ricovero": "2023",
        "Numero Ricovero": "33456",
        "Regime": "Urgenza",
        "Data Ricovero": "05/06/2023",
        "Reparto Accettazione": "Chirurgia Generale",
        "Tipo Ricovero": "Urgenza",
        "Reparto Dimissione": "Chirurgia Generale",
        "Data Dimissione": "10/06/2023",
        "Anamnesi": "Pregressa appendicectomia, dolore addominale acuto.",
        "Diagnosi": "Ermia inguinale strozzata.",
        "Terapia": "Ernioplastica.",
        "Keywords": "Infezione",
        "Nome": "Marco",
        "Cognome": "Rossi",
        "Sesso": "M",
        "Data di nascita": "15/03/1970",
        "Codice Fiscale": "RSSMRC70C15H501U",
        "_id": "RSSMRC70C15H501U_99456"
    },
    {
        "URI": "medical_record_20.pdf",
        "UDA": "99567",
        "Anno Ricovero": "2020",
        "Numero Ricovero": "44567",
        "Regime": "Day Hospital.",
        "Data Ricovero": "12/07/2020",
        "Reparto Accettazione": "Dermatologia",
        "Tipo Ricovero": "Ordinario",
        "Reparto Dimissione": "Dermatologia",
        "Data Dimissione": "14/07/2020",
        "Anamnesi": "Psoriasi a placche cronica.",
        "Diagnosi": "Peggioramento psoriasi con lesioni estese.",
        "Terapia": "Terapia biologica con inibitori TNF-alfa.",
        "Keywords": "Psoriasi, lesioni estese.",
        "Nome": "Marco",
        "Cognome": "Rossi",
        "Sesso": "M",
        "Data di nascita": "15/03/1970",
        "Codice Fiscale": "RSSMRC70C15H501U",
        "_id": "RSSMRC70C15H501U_99567"
    }
]);